GET http://localhost:8081/hello/get
#Accept: application/json
###
POST http://localhost:8081/hello/post
Content-Type:application/x-www-form-urlencoded

map=Test
###
GET http://localhost:8081/hello/test
